/* eslint-disable import/no-commonjs, import/unambiguous */
module.exports = {
    env: {
        es2021: true,
        node:   true,
    },
    parserOptions: {
        sourceType: 'module',
    },
    plugins: [
        'import',
    ],
    settings: {
        'import/resolver': {
            node: {},
        },
    },
    rules: {
        /* eslint-disable array-bracket-newline, no-magic-numbers */
        // Possible Errors (https://eslint.org/docs/rules/#possible-errors)
        'no-await-in-loop':            ['error'],
        'no-console':                  ['warn'],
        'no-extra-parens':             ['error'],
        'no-loss-of-precision':        ['error'],
        'no-promise-executor-return':  ['error'],
        'no-unsafe-optional-chaining': ['error',
            {
                disallowArithmeticOperators: true,
            },
        ],
        'require-atomic-updates': ['error'],

        // Best Practices (https://eslint.org/docs/rules/#best-practices)
        'accessor-pairs':        ['error'],
        'array-callback-return': ['error',
            {
                checkForEach: true,
            },
        ],
        'block-scoped-var':       ['error'],
        'class-methods-use-this': ['error'],
        'consistent-return':      ['error'],
        'curly':                  ['error',
            'multi-line',
            'consistent',
        ],
        'default-case':           ['error'],
        'default-case-last':      ['error'],
        'default-param-last':     ['error'],
        'dot-location':           ['error'],
        'dot-notation':           ['error'],
        'eqeqeq':                 ['error'],
        'grouped-accessor-pairs': ['error',
            'getBeforeSet',
        ],
        'guard-for-in':               ['error'],
        'max-classes-per-file':       ['warn'],
        'no-alert':                   ['warn'],
        'no-caller':                  ['error'],
        'no-constructor-return':      ['error'],
        'no-div-regex':               ['error'],
        'no-else-return':             ['error'],
        'no-empty-function':          ['error'],
        'no-eq-null':                 ['error'],
        'no-eval':                    ['error'],
        'no-extend-native':           ['error'],
        'no-extra-bind':              ['error'],
        'no-extra-label':             ['error'],
        'no-floating-decimal':        ['error'],
        'no-implicit-coercion':       ['error'],
        'no-implicit-globals':        ['error'],
        'no-implied-eval':            ['error'],
        'no-invalid-this':            ['error'],
        'no-iterator':                ['error'],
        'no-labels':                  ['error'],
        'no-lone-blocks':             ['error'],
        'no-loop-func':               ['error'],
        'no-magic-numbers':           ['error'],
        'no-multi-spaces':            ['error'],
        'no-multi-str':               ['error'],
        'no-new':                     ['error'],
        'no-new-func':                ['error'],
        'no-new-wrappers':            ['error'],
        'no-nonoctal-decimal-escape': ['error'],
        'no-octal-escape':            ['error'],
        'no-param-reassign':          ['error'],
        'no-proto':                   ['error'],
        'no-return-assign':           ['error',
            'always',
        ],
        'no-return-await':              ['error'],
        'no-script-url':                ['error'],
        'no-self-compare':              ['error'],
        'no-sequences':                 ['error'],
        'no-throw-literal':             ['error'],
        'no-unmodified-loop-condition': ['error'],
        'no-unused-expressions':        ['error'],
        'no-useless-call':              ['error'],
        'no-useless-concat':            ['error'],
        'no-useless-return':            ['error'],
        'no-void':                      ['error'],
        'prefer-named-capture-group':   ['error'],
        'prefer-promise-reject-errors': ['error'],
        'prefer-regex-literals':        ['error',
            {
                disallowRedundantWrapping: true,
            },
        ],
        'radix':                  ['error'],
        'require-await':          ['error'],
        'require-unicode-regexp': ['error'],
        'vars-on-top':            ['error'],
        'wrap-iife':              ['error'],
        'yoda':                   ['error'],

        // Strict Mode (https://eslint.org/docs/rules/#strict-mode)
        'strict': ['error', 'never'],

        // Variables (https://eslint.org/docs/rules/#variables)
        'init-declarations':    ['error'],
        'no-label-var':         ['error'],
        'no-shadow':            ['error'],
        'no-undef-init':        ['error'],
        'no-undefined':         ['error'],
        'no-use-before-define': ['error'],

        // Stylistic Issues (https://eslint.org/docs/rules/#stylistic-issues)
        'array-bracket-newline': ['error',
            'consistent',
        ],
        'array-bracket-spacing': ['error'],
        'array-element-newline': ['error',
            'consistent',
        ],
        'block-spacing': ['error'],
        'brace-style':   ['error',
            '1tbs',
            {
                allowSingleLine: true,
            },
        ],
        'camelcase':            ['error'],
        'capitalized-comments': ['error',
            'always',
            {
                ignorePattern: '^\\s*(?:spell-checker:)',
            },
        ],
        'comma-dangle': ['error',
            'always-multiline',
        ],
        'comma-spacing':             ['error'],
        'comma-style':               ['error'],
        'computed-property-spacing': ['error'],
        'consistent-this':           ['error'],
        'eol-last':                  ['error'],
        'func-call-spacing':         ['error'],
        'func-name-matching':        ['error'],
        'func-names':                ['error',
            'as-needed',
        ],
        'func-style': ['error',
            'declaration',
        ],
        'function-call-argument-newline': ['error',
            'consistent',
        ],
        'function-paren-newline':   ['error'],
        'implicit-arrow-linebreak': ['error'],
        'indent':                   ['error',
            4,
        ],
        'key-spacing': ['error',
            {
                align: 'value',
            },
        ],
        'keyword-spacing':      ['error'],
        'lines-around-comment': ['error',
            {
                beforeBlockComment: true,
                beforeLineComment:  true,
                allowBlockStart:    true,
                allowObjectStart:   true,
                allowArrayStart:    true,
                allowClassStart:    true,
                ignorePattern:      '^\\s*(?:spell-checker:)',
            },
        ],
        'lines-between-class-members': ['error'],
        'max-depth':                   ['warn'],
        'max-len':                     ['warn',
            {
                code:                   128,
                ignoreUrls:             true,
                ignoreStrings:          true,
                ignoreTemplateLiterals: true,
                ignoreRegExpLiterals:   true,
                ignorePattern:          '^(?: *\\/\\* eslint-(?:dis|en)able .+ \\*\\/| *\\/\\/ eslint-disable-next-line .+)$',
            },
        ],
        'max-lines': ['warn',
            {
                max:            512,
                skipBlankLines: true,
                skipComments:   true,
            },
        ],
        'max-lines-per-function': ['warn',
            {
                max:            64,
                skipBlankLines: true,
                skipComments:   true,
                IIFEs:          true,
            },
        ],
        'max-nested-callbacks': ['warn'],
        'max-params':           ['warn'],
        'max-statements':       ['warn',
            {
                max: 16,
            },
        ],
        'max-statements-per-line': ['warn'],
        'multiline-comment-style': ['error'],
        'multiline-ternary':       ['error',
            'always-multiline',
        ],
        'new-cap':                  ['error'],
        'new-parens':               ['error'],
        'newline-per-chained-call': ['error'],
        'no-array-constructor':     ['error'],
        'no-bitwise':               ['error'],
        'no-continue':              ['error'],
        'no-inline-comments':       ['error',
            {
                ignorePattern: 'NOTE|OPTIMIZE|TODO|HACK|XXX|FIXME|BUG',
            },
        ],
        'no-lonely-if':                     ['error'],
        'no-mixed-operators':               ['error'],
        'no-multi-assign':                  ['error'],
        'no-multiple-empty-lines':          ['error'],
        'no-negated-condition':             ['error'],
        'no-new-object':                    ['error'],
        'no-plusplus':                      ['error'],
        'no-tabs':                          ['error'],
        'no-trailing-spaces':               ['error'],
        'no-underscore-dangle':             ['error'],
        'no-unneeded-ternary':              ['error'],
        'no-whitespace-before-property':    ['error'],
        'nonblock-statement-body-position': ['error'],
        'object-curly-newline':             ['error',
            {
                multiline:  true,
                consistent: true,
            },
        ],
        'object-curly-spacing':    ['error'],
        'object-property-newline': ['error'],
        'one-var':                 ['error',
            {
                initialized:   'never',
                uninitialized: 'always',
            },
        ],
        'one-var-declaration-per-line': ['error'],
        'operator-assignment':          ['error'],
        'operator-linebreak':           ['error',
            'after',
        ],
        'padded-blocks': ['error',
            'never',
        ],
        'padding-line-between-statements': ['error'],
        'prefer-exponentiation-operator':  ['error'],
        'prefer-object-spread':            ['error'],
        'quote-props':                     ['error',
            'consistent-as-needed',
        ],
        'quotes': ['error',
            'single',
        ],
        'semi':                        ['error'],
        'semi-spacing':                ['error'],
        'semi-style':                  ['error'],
        'sort-vars':                   ['error'],
        'space-before-blocks':         ['error'],
        'space-before-function-paren': ['error',
            {
                anonymous:  'always',
                named:      'never',
                asyncArrow: 'always',
            },
        ],
        'space-in-parens':      ['error'],
        'space-infix-ops':      ['error'],
        'space-unary-ops':      ['error'],
        'spaced-comment':       ['error'],
        'switch-colon-spacing': ['error'],
        'template-tag-spacing': ['error'],
        'wrap-regex':           ['error'],

        // ECMAScript 6 (https://eslint.org/docs/rules/#ecmascript-6)
        'arrow-body-style':       ['error'],
        'arrow-parens':           ['error'],
        'arrow-spacing':          ['error'],
        'generator-star-spacing': ['error'],
        'no-confusing-arrow':     ['error'],
        'no-duplicate-imports':   ['error',
            {
                includeExports: true,
            },
        ],
        'no-useless-computed-key': ['error',
            {
                enforceForClassMembers: true,
            },
        ],
        'no-useless-constructor': ['error'],
        'no-useless-rename':      ['error'],
        'no-var':                 ['error'],
        'object-shorthand':       ['error'],
        'prefer-arrow-callback':  ['error',
            {
                allowUnboundThis: false,
            },
        ],
        'prefer-const': ['error',
            {
                destructuring: 'all',
            },
        ],
        'prefer-destructuring':    ['error'],
        'prefer-numeric-literals': ['error'],
        'prefer-rest-params':      ['error'],
        'prefer-spread':           ['error'],
        'prefer-template':         ['error'],
        'rest-spread-spacing':     ['error'],
        'sort-imports':            ['error',
            {
                allowSeparatedGroups:  true,
                ignoreDeclarationSort: true,
            },
        ],
        'symbol-description':     ['error'],
        'template-curly-spacing': ['error'],
        'yield-star-spacing':     ['error'],

        // Import static analysis
        'import/no-unresolved':            ['error'],
        'import/named':                    ['error'],
        'import/default':                  ['error'],
        'import/namespace':                ['error'],
        'import/no-absolute-path':         ['error'],
        'import/no-dynamic-require':       ['error'],
        'import/no-self-import':           ['error'],
        'import/no-useless-path-segments': ['error',
            {
                noUselessIndex: true,
            },
        ],
        'import/no-relative-packages': ['error'],

        // Import helpful warnings
        'import/export':                     ['error'],
        'import/no-named-as-default':        ['error'],
        'import/no-named-as-default-member': ['error'],
        'import/no-deprecated':              ['error'],
        'import/no-extraneous-dependencies': ['error'],
        'import/no-mutable-exports':         ['error'],
        'import/no-unused-modules':          ['error'],

        // Import module systems
        'import/unambiguous':              ['error'],
        'import/no-commonjs':              ['error'],
        'import/no-amd':                   ['error'],
        'import/no-nodejs-modules':        ['error'],
        'import/no-import-module-exports': ['error'],

        // Import style guide
        'import/first':         ['error'],
        'import/no-duplicates': ['error'],
        'import/no-namespace':  ['error'],
        'import/extensions':    ['error'],
        'import/order':         ['error',
            {
                'groups': [
                    'builtin',
                    'external',
                    'internal',
                    'parent',
                    'sibling',
                    'index',
                    'object',
                    'type',
                    'unknown',
                ],
                'alphabetize': {
                    order: 'asc',
                },
                'newlines-between': 'never',
            },
        ],
        'import/newline-after-import': ['error'],
        'import/max-dependencies':     ['warn',
            {
                max:               8,
                ignoreTypeImports: true,
            },
        ],
        'import/no-unassigned-import':        ['error'],
        'import/no-named-default':            ['error'],
        'import/no-anonymous-default-export': ['error'],
        /* eslint-enable */
    },
};
